services:
  thercio-landing:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3003:3003"
    networks:
      - pi_default

networks:
  pi_default:
    external: true